# Generated by Django 4.0.4 on 2022-06-13 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militant',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 5, 47, 22, 566399)),
        ),
    ]
